SPOONACULAR_API_KEY=placeholder
usda_api_key=placeholder
fatsecret_api_client-id=d8d9276de60e444e8dfb4b3bfe0ab6a4
fatsecret_api_client-secret=1ce18512619c4d97ad909dca9f2cdba5
GOOGLE_CLIENT_ID=placeholder
GOOGLE_CLIENT_SECRET=placeholder
