DB_USERNAME=your_mysql_username
DB_PASSWORD=your_mysql_password
SPOONACULAR_API_KEY=your_spoonacular_api_key
usda_api_key=your_usda_api_key
fatsecret_api_client-id=your_fatsecret_client_id
fatsecret_api_client-secret=your_fatsecret_client_secret
GOOGLE_CLIENT_ID=your_google_client_id
GOOGLE_CLIENT_SECRET=your_google_client_secret
